name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  fugitiva:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17 # Latest LTS up to 2023-09
        cache: sbt
    - name: Compile Fugitiva
      working-directory: code
      run: sbt -v "fugitivaJVM/compile"
  test-rfc4648:
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 11 # LTS up to 2023-09
          - java: 17 # LTS up to 2026-09
          - java: 20 # Latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
        cache: sbt
    - name: Compile rfc4648
      working-directory: code
      run: sbt -v "rfc4648JVM/compile"
    - name: Test rfc4648
      working-directory: code
      run: sbt -v "rfc4648JVM/test" "rfc4648JS/test" "rfc4648Native/test"
  test-toml:
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 11 # LTS up to 2023-09
          - java: 17 # LTS up to 2026-09
          - java: 20 # Latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
        cache: sbt
    - name: Compile TOML
      working-directory: code
      run: sbt -v "tomlJVM/compile" "toml-tomltestJVM/compile" "toml-parse-benchJVM/compile"
    - name: Test TOML/parse
      working-directory: code
      run: sbt -v "toml-parseJVM/test" "toml-parseJS/test" "toml-parseNative/test"
  test-uuidv7:
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 11 # LTS up to 2023-09
          - java: 17 # LTS up to 2026-09
          - java: 20 # Latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
        cache: sbt
    - name: Compile uuidv7
      working-directory: code
      run: sbt -v "uuidv7JVM/compile"
    - name: Test uuidv7
      working-directory: code
      run: sbt -v "uuidv7JVM/test" "uuidv7JS/test" "uuidv7Native/test"
