name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-rfc4648:
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 11 # LTS up to 2023-09
          - java: 17 # LTS up to 2026-09
          - java: 20 # Latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
        cache: sbt
    - name: Compile rfc4648
      run: sbt -v "rfc4648JVM/compile"
    - name: Test rfc4648
      run: sbt -v "rfc4648JVM/test" "rfc4648JS/test" "rfc4648Native/test"
