name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 11 # LTS up to 2023-09
          - java: 17 # LTS up to 2026-09
          - java: 20 # Latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
        cache: sbt
    - name: Test toml/parse
      working-directory: code
      run: sbt -v "toml-parseJVM/test" "toml-parseJS/test" "toml-parseNative/test"
